"""Add created_at column to scripts

Revision ID: 11af589b0da7
Revises: 64468807e4fd
Create Date: 2024-09-05 10:20:29.966491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11af589b0da7'
down_revision: Union[str, None] = '64468807e4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'created_at')
    # ### end Alembic commands ###
