"""Add research_url to Script model

Revision ID: 64468807e4fd
Revises: 4b2caad877ec
Create Date: 2024-09-05 09:50:11.722514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64468807e4fd'
down_revision: Union[str, None] = '4b2caad877ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('research_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'research_url')
    # ### end Alembic commands ###
