"""Add foreign key to Script model

Revision ID: 7d32905724e4
Revises: 
Create Date: 2024-09-05 09:08:28.777842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d32905724e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('script')
    op.drop_table('show_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('host1', sa.VARCHAR(length=150), nullable=True),
    sa.Column('host1_voice', sa.VARCHAR(length=150), nullable=True),
    sa.Column('host1_personality', sa.TEXT(), nullable=True),
    sa.Column('host2', sa.VARCHAR(length=150), nullable=True),
    sa.Column('host2_voice', sa.VARCHAR(length=150), nullable=True),
    sa.Column('host2_personality', sa.TEXT(), nullable=True),
    sa.Column('host3', sa.VARCHAR(length=150), nullable=True),
    sa.Column('host3_voice', sa.VARCHAR(length=150), nullable=True),
    sa.Column('host3_personality', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('podcast_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('research_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('audio', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
