"""Add foreign key to Script model

Revision ID: d5fd1c89e6e3
Revises: 287a98f34742
Create Date: 2024-09-05 09:15:40.771531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fd1c89e6e3'
down_revision: Union[str, None] = '287a98f34742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('podcast')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('host1', sa.TEXT(), nullable=True),
    sa.Column('host2', sa.TEXT(), nullable=True),
    sa.Column('host3', sa.TEXT(), nullable=True),
    sa.Column('research', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
